//    uniCenta oPOS  - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2013 uniCenta & previous Openbravo POS works
//    http://www.unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.scale;

import com.openbravo.beans.LocaleResources;
import com.openbravo.beans.RoundedBorder;
import com.openbravo.format.Formats;
import com.openbravo.pos.ticket.ProductInfoExt;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.Icon;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Erik Beugelaar
 */
public class JDialogScale extends javax.swing.JDialog {
    
    private static LocaleResources m_resources;
    
    private static JDialogScale myMsg;     // 01-02-2014 De Kruidenier
    private static Double m_value;
    private static ProductInfoExt m_product;
    
    /** Creates new form JNumberDialog */
    public JDialogScale(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        init();
    }
    
    /** Creates new form JNumberDialog */
    public JDialogScale(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        init();
    }
    
    private void init() {
        
        if (m_resources == null) {
            m_resources = new LocaleResources();
            m_resources.addBundleName("beans_messages");
        }
        
        initComponents();        
        getRootPane().setDefaultButton(jcmdOK);   
        
        m_jnumber.reset();
        m_jnumber.setDoubleValue(0.0);
        
        m_jPanelTitle.setBorder(RoundedBorder.createGradientBorder());

        m_value = null;
    }
    
    // 05-02-2014 De Kruidenier
    private void updateTitle(String title, String message, Icon icon) {
        setTitle(title);
        m_lblMessage.setText(message);
        m_lblMessage.setIcon(icon);
    }

    private void updatePrice(Double number) {
        if (number != null) {
            //Formats.CURRENCY.formatValue(number * m_product.getPriceSell());
            m_jPrice.setText(Formats.CURRENCY.formatValue(number * m_product.getPriceSell()));
        } else {
            m_jPrice.setText("0");
        }
    }
    
    // 01-02-2014 De Kruidenier
    private void updateNumber(Double number) {
        m_jnumber.setDoubleValue(number);
        
        m_value = m_jnumber.getDoubleValue();

        // Update price
        updatePrice(m_value);
    }
    
    // 01-02-2014 De Kruidenier
    public static void setTitle(String title, String message, Icon icon) {
        myMsg.updateTitle(title, message, icon);
     }
    
    // 01-02-2014 De Kruidenier
    public static void setNumber(Double number) {
        myMsg.updateNumber(number);
     }
    
    /*
    public static Double showEditNumber(Component parent, String title) {
        return showEditNumber(parent, title, null, null, null);
    }
    public static Double showEditNumber(Component parent, String title, String message) {
        return showEditNumber(parent, title, message, null,null);
    }
    
    public static Double showEditNumber(Component parent, String title, String message, Icon icon) {
        return showEditNumber(parent, title, message, icon, null);
    }
    */
    
    public static Double showEditNumber(Component parent, String title, String message, Icon icon, ProductInfoExt product) {
        
        Window window = SwingUtilities.windowForComponent(parent);
        
        // JNumberDialog myMsg;
        if (window instanceof Frame) { 
            myMsg = new JDialogScale((Frame) window, true);
        } else {
            myMsg = new JDialogScale((Dialog) window, true);
        }
        
        myMsg.m_product = product;
       
        myMsg.jLabelNameValue.setText(product.getName());
        myMsg.setTitle(title, message, icon);
        myMsg.setVisible(true);
        
        return myMsg.m_value;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcmdOK = new javax.swing.JButton();
        jcmdCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelGrid = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelWeight = new javax.swing.JLabel();
        jLabelNameValue = new javax.swing.JLabel();
        m_jnumber = new com.openbravo.editor.JEditorDoublePositive();
        m_jPrice = new javax.swing.JTextField();
        m_jPanelTitle = new javax.swing.JPanel();
        m_lblMessage = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jcmdOK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcmdOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/ok.png"))); // NOI18N
        jcmdOK.setText(m_resources.getString("button.ok")); // NOI18N
        jcmdOK.setMargin(new java.awt.Insets(8, 16, 8, 16));
        jcmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdOKActionPerformed(evt);
            }
        });
        jPanel1.add(jcmdOK);

        jcmdCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/cancel.png"))); // NOI18N
        jcmdCancel.setText(m_resources.getString("button.cancel")); // NOI18N
        jcmdCancel.setMargin(new java.awt.Insets(8, 16, 8, 16));
        jcmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jcmdCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanelGrid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanelGrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jPanelGrid.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 5, -1, -1));

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        jLabelPrice.setText(bundle.getString("label.prodpriceselltax")); // NOI18N
        jPanelGrid.add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, 40));

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelName.setText(bundle.getString("label.prodname")); // NOI18N
        jPanelGrid.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        jLabelWeight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelWeight.setText(bundle.getString("label.scaleweight")); // NOI18N
        jPanelGrid.add(jLabelWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 40));

        jLabelNameValue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNameValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNameValue.setAlignmentX(0.5F);
        jPanelGrid.add(jLabelNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 270, 40));

        m_jnumber.setFocusable(false);
        m_jnumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanelGrid.add(m_jnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 150, 40));

        m_jPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        m_jPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        m_jPrice.setToolTipText("");
        m_jPrice.setFocusable(false);
        jPanelGrid.add(m_jPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 120, 40));

        jPanel2.add(jPanelGrid, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        m_jPanelTitle.setLayout(new java.awt.BorderLayout());

        m_lblMessage.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.darkGray), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        m_jPanelTitle.add(m_lblMessage, java.awt.BorderLayout.CENTER);

        getContentPane().add(m_jPanelTitle, java.awt.BorderLayout.NORTH);

        setSize(new java.awt.Dimension(504, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdOKActionPerformed

        //m_value = 0.0;
        m_value = m_jnumber.getDoubleValue();
        setVisible(false);
        dispose();

        
    }//GEN-LAST:event_jcmdOKActionPerformed

    private void jcmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdCancelActionPerformed
        
        updateNumber(null);     // 01-02-2014 De Kruidenier
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_jcmdCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        updateNumber(null);     // 01-02-2014 De Kruidenier
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_formWindowClosing
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameValue;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelWeight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelGrid;
    private javax.swing.JButton jcmdCancel;
    private javax.swing.JButton jcmdOK;
    private javax.swing.JPanel m_jPanelTitle;
    private javax.swing.JTextField m_jPrice;
    private com.openbravo.editor.JEditorDoublePositive m_jnumber;
    private javax.swing.JLabel m_lblMessage;
    // End of variables declaration//GEN-END:variables
    
}
